#spring.profiles.active=prod


# Server
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/lms_db
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT
jwt.secret= oisdhfoihwe98fh9wahfhwez9fya9wef97weyf79y9ayf89

aws.s3.bucket-name=test-bucket
aws.region=eu-north-1
aws.access-key=test
aws.secret-key=test